n1 = int(input('Digite um número: '))
um = n1*1
dois = n1*2
tres = n1*3
quatro = n1*4
cinco = n1*5
seis = n1*6
sete = n1*7
oito = n1*8
nove = n1*9
print('{}x1={}'.format(n1,um))
print('{}x2={}'.format(n1,dois))
print('{}x3={}'.format(n1,tres))
print('{}x4={}'.format(n1,quatro))
print('{}x5={}'.format(n1,cinco))
print('{}x6={}'.format(n1,seis))
print('{}x7={}'.format(n1,sete))
print('{}x8={}'.format(n1,oito))
print('{}x9={}'.format(n1,nove))
